# nutrients_data.py
# Comprehensive nutrient reference data with RDA values, time windows, food sources, and deficiency diseases.

NUTRIENTS: dict[str, dict] = {
    # ── Macronutrients ────────────────────────────────────────────────────────
    "protein": {
        "name": "蛋白质 (Protein)",
        "unit": "g",
        "rda_per_day": 50.0,
        "time_window_days": 1,
        "reference": "WHO/FAO 0.83 g/kg/day; 50g based on ~60kg reference adult.",
        "deficiency_diseases": [
            "夸希奥科病 Kwashiorkor（重度蛋白质缺乏，腹水、水肿）",
            "肌肉萎缩 Muscle Wasting / Sarcopenia",
            "免疫力下降，易反复感染",
            "伤口愈合缓慢，贫血",
        ],
        "sources": [
            {"food": "鸡胸肉 (Chicken Breast)", "per_100g": 31.0},
            {"food": "金枪鱼 (Tuna)", "per_100g": 29.0},
            {"food": "鸡蛋 (Egg)", "per_100g": 13.0},
            {"food": "希腊酸奶 (Greek Yogurt)", "per_100g": 10.0},
            {"food": "老豆腐 (Firm Tofu)", "per_100g": 8.0},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 9.0},
        ],
    },
    "fat": {
        "name": "脂肪 (Fat)",
        "unit": "g",
        "rda_per_day": 65.0,
        "time_window_days": 1,
        "reference": "AMDR 20-35% of 2000 kcal energy intake; 65g is midpoint estimate.",
        "deficiency_diseases": [
            "脂溶性维生素（A/D/E/K）吸收障碍，继发多种缺乏症",
            "必需脂肪酸缺乏性皮炎、脱发",
            "性激素合成受阻，生殖功能异常",
            "细胞膜结构受损，神经传导异常",
        ],
        "sources": [
            {"food": "橄榄油 (Olive Oil)", "per_100g": 100.0},
            {"food": "核桃 (Walnuts)", "per_100g": 65.0},
            {"food": "牛油果 (Avocado)", "per_100g": 15.0},
            {"food": "三文鱼 (Salmon)", "per_100g": 13.0},
            {"food": "鸡蛋 (Egg)", "per_100g": 11.0},
        ],
    },
    "carbohydrates": {
        "name": "碳水化合物 (Carbohydrates)",
        "unit": "g",
        "rda_per_day": 260.0,
        "time_window_days": 1,
        "reference": "IOM RDA 130g minimum; 260g based on 52% of 2000 kcal diet.",
        "deficiency_diseases": [
            "低血糖 Hypoglycemia（头晕、心悸、意识模糊）",
            "肌肉蛋白分解供能，体重下降、肌无力",
            "酮症 Ketosis（酮体升高，口气异常、疲劳）",
        ],
        "sources": [
            {"food": "白米饭(熟) (White Rice Cooked)", "per_100g": 28.0},
            {"food": "燕麦(干) (Oats Dry)", "per_100g": 66.0},
            {"food": "全麦面包 (Whole Wheat Bread)", "per_100g": 43.0},
            {"food": "红薯(熟) (Sweet Potato Cooked)", "per_100g": 20.0},
            {"food": "香蕉 (Banana)", "per_100g": 23.0},
        ],
    },
    "fiber": {
        "name": "膳食纤维 (Fiber)",
        "unit": "g",
        "rda_per_day": 25.0,
        "time_window_days": 1,
        "reference": "IOM AI: 25g/day for women, 38g/day for men; 25g is conservative shared target.",
        "deficiency_diseases": [
            "便秘、痔疮、憩室病",
            "结直肠癌风险显著升高",
            "血脂异常（LDL升高），心血管疾病风险增加",
            "血糖调节受损，2型糖尿病风险升高",
        ],
        "sources": [
            {"food": "燕麦(干) (Oats Dry)", "per_100g": 10.6},
            {"food": "全麦面包 (Whole Wheat Bread)", "per_100g": 6.0},
            {"food": "红薯(熟) (Sweet Potato Cooked)", "per_100g": 3.0},
            {"food": "西兰花 (Broccoli)", "per_100g": 2.6},
            {"food": "苹果 (Apple)", "per_100g": 2.4},
        ],
    },
    "sugar": {
        "name": "糖 (Sugar)",
        "unit": "g",
        "rda_per_day": 50.0,
        "upper_limit": True,
        "time_window_days": 1,
        "reference": "WHO 2015: free sugars < 10% total energy (ideally < 5%); 50g is the daily cap for 2000 kcal diet.",
        "deficiency_diseases": [
            "无缺乏症风险 — 糖有最低摄入量无意义",
            "过量危害：龋齿、肥胖、2型糖尿病、非酒精性脂肪肝、心血管疾病风险升高",
        ],
        "sources": [
            {"food": "白砂糖 (White Sugar)", "per_100g": 100.0},
            {"food": "蜂蜜 (Honey)", "per_100g": 82.0},
            {"food": "香蕉 (Banana)", "per_100g": 12.2},
            {"food": "苹果 (Apple)", "per_100g": 10.4},
            {"food": "橙子 (Orange)", "per_100g": 9.4},
            {"food": "黑巧克力70% (Dark Chocolate)", "per_100g": 21.7},
        ],
    },
    # ── Vitamins ──────────────────────────────────────────────────────────────
    "vitamin_a": {
        "name": "维生素A (Vitamin A)",
        "unit": "mcg_rae",
        "rda_per_day": 800.0,
        "time_window_days": 7,
        "reference": "IOM RDA 700-900 mcg RAE/day; fat-soluble, liver stores last 1-2 weeks.",
        "deficiency_diseases": [
            "夜盲症 Night Blindness（最早期症状）",
            "眼干燥病 Xerophthalmia → 角膜软化症，严重可致失明",
            "皮肤角化过度，毛囊角化",
            "感染易感性升高（呼吸道、消化道黏膜受损）",
        ],
        "sources": [
            {"food": "牛肝 (Beef Liver)", "per_100g": 4968.0},
            {"food": "红薯(熟) (Sweet Potato Cooked)", "per_100g": 961.0},
            {"food": "胡萝卜 (Carrot)", "per_100g": 835.0},
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 524.0},
            {"food": "南瓜(熟) (Pumpkin Cooked)", "per_100g": 426.0},
        ],
    },
    "vitamin_c": {
        "name": "维生素C (Vitamin C)",
        "unit": "mg",
        "rda_per_day": 90.0,
        "time_window_days": 1,
        "reference": "IOM RDA 75-90 mg/day; water-soluble, body pool depletes in 4-6 weeks but daily intake optimal.",
        "deficiency_diseases": [
            "坏血病 Scurvy（牙龈出血、关节肿痛、皮下淤血、牙齿松动）",
            "胶原蛋白合成障碍 → 伤口愈合极慢",
            "免疫功能下降，易疲劳、抑郁",
        ],
        "sources": [
            {"food": "红甜椒 (Red Bell Pepper)", "per_100g": 128.0},
            {"food": "西兰花 (Broccoli)", "per_100g": 89.0},
            {"food": "猕猴桃 (Kiwifruit)", "per_100g": 93.0},
            {"food": "橙子 (Orange)", "per_100g": 53.0},
            {"food": "草莓 (Strawberries)", "per_100g": 59.0},
        ],
    },
    "vitamin_d": {
        "name": "维生素D (Vitamin D)",
        "unit": "mcg",
        "rda_per_day": 15.0,
        "time_window_days": 7,
        "reference": "IOM RDA 600 IU = 15 mcg/day; fat-soluble, half-life ~2-3 weeks allows weekly tracking.",
        "deficiency_diseases": [
            "佝偻病 Rickets（儿童骨骼变形、O型腿）",
            "骨软化症 Osteomalacia（成人骨痛、肌无力）",
            "骨质疏松症，骨折风险增加",
            "免疫功能下降，抑郁、慢性疲劳",
            "自身免疫性疾病风险升高（多发性硬化等）",
        ],
        "sources": [
            {"food": "三文鱼 (Salmon)", "per_100g": 11.1},
            {"food": "沙丁鱼罐头 (Canned Sardines)", "per_100g": 4.8},
            {"food": "金枪鱼罐头 (Canned Tuna)", "per_100g": 3.7},
            {"food": "蛋黄 (Egg Yolk)", "per_100g": 5.4},
            {"food": "强化牛奶 (Fortified Milk)", "per_100g": 1.0},
        ],
    },
    "vitamin_e": {
        "name": "维生素E (Vitamin E)",
        "unit": "mg",
        "rda_per_day": 15.0,
        "time_window_days": 7,
        "reference": "IOM RDA 15 mg/day alpha-tocopherol; fat-soluble, stored in adipose tissue, weekly window sufficient.",
        "deficiency_diseases": [
            "周围神经病变 Peripheral Neuropathy（手足麻木、共济失调）",
            "溶血性贫血（尤其新生儿）",
            "视网膜病变，视力受损",
            "免疫反应减弱",
        ],
        "sources": [
            {"food": "杏仁 (Almonds)", "per_100g": 25.6},
            {"food": "花生 (Peanuts)", "per_100g": 8.3},
            {"food": "葵花籽油 (Sunflower Oil)", "per_100g": 41.1},
            {"food": "菠菜 (Spinach)", "per_100g": 2.1},
            {"food": "鸡蛋 (Egg)", "per_100g": 1.1},
        ],
    },
    "vitamin_k": {
        "name": "维生素K (Vitamin K)",
        "unit": "mcg",
        "rda_per_day": 110.0,
        "time_window_days": 7,
        "reference": "IOM AI 90-120 mcg/day; fat-soluble with modest liver storage, weekly assessment appropriate.",
        "deficiency_diseases": [
            "凝血障碍 Coagulopathy（轻微碰伤大面积淤血，出血难止）",
            "骨质疏松症，骨折风险升高（影响骨钙素活化）",
            "新生儿维生素K缺乏性出血（VKDB）",
        ],
        "sources": [
            {"food": "羽衣甘蓝 (Kale)", "per_100g": 817.0},
            {"food": "菠菜 (Spinach)", "per_100g": 483.0},
            {"food": "西兰花 (Broccoli)", "per_100g": 102.0},
            {"food": "卷心菜 (Cabbage)", "per_100g": 76.0},
            {"food": "牛油果 (Avocado)", "per_100g": 21.0},
        ],
    },
    "vitamin_b1": {
        "name": "维生素B1 (Vitamin B1 / Thiamine)",
        "unit": "mg",
        "rda_per_day": 1.2,
        "time_window_days": 1,
        "reference": "IOM RDA 1.1-1.2 mg/day; water-soluble, body stores deplete within 18 days, daily tracking recommended.",
        "deficiency_diseases": [
            "脚气病 Beriberi（干型：神经炎；湿型：心脏扩大、充血性心衰）",
            "韦尼克脑病 Wernicke Encephalopathy（眼球震颤、共济失调、意识障碍）",
            "科尔萨科夫综合征 Korsakoff Syndrome（记忆障碍）",
        ],
        "sources": [
            {"food": "猪肉 (Pork)", "per_100g": 0.87},
            {"food": "燕麦 (Oats)", "per_100g": 0.76},
            {"food": "全麦面包 (Whole Wheat Bread)", "per_100g": 0.38},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 0.17},
            {"food": "鸡蛋 (Egg)", "per_100g": 0.05},
        ],
    },
    "vitamin_b2": {
        "name": "维生素B2 (Vitamin B2 / Riboflavin)",
        "unit": "mg",
        "rda_per_day": 1.3,
        "time_window_days": 1,
        "reference": "IOM RDA 1.1-1.3 mg/day; water-soluble, minimal storage, daily intake required.",
        "deficiency_diseases": [
            "核黄素缺乏症 Ariboflavinosis（口角炎、唇干裂）",
            "舌炎（草莓舌、地图舌）",
            "脂溢性皮炎，眼角膜血管增生",
            "贫血（影响铁的代谢）",
        ],
        "sources": [
            {"food": "鸡蛋 (Egg)", "per_100g": 0.46},
            {"food": "牛奶 (Milk)", "per_100g": 0.18},
            {"food": "牛肉 (Beef)", "per_100g": 0.20},
            {"food": "杏仁 (Almonds)", "per_100g": 1.01},
            {"food": "牛肝 (Beef Liver)", "per_100g": 3.08},
        ],
    },
    "vitamin_b3": {
        "name": "维生素B3 (Vitamin B3 / Niacin)",
        "unit": "mg_ne",
        "rda_per_day": 16.0,
        "time_window_days": 1,
        "reference": "IOM RDA 14-16 mg NE/day; water-soluble, negligible storage, daily monitoring appropriate.",
        "deficiency_diseases": [
            "糙皮病 Pellagra（3D症状：皮炎 Dermatitis、腹泻 Diarrhea、痴呆 Dementia）",
            "严重时可致死亡（第4个D：Death）",
            "光敏性皮炎（暴露部位皮肤增厚变黑）",
        ],
        "sources": [
            {"food": "金枪鱼 (Tuna)", "per_100g": 18.5},
            {"food": "鸡胸肉 (Chicken Breast)", "per_100g": 13.4},
            {"food": "花生 (Peanuts)", "per_100g": 13.8},
            {"food": "猪肉 (Pork)", "per_100g": 6.3},
            {"food": "牛肉 (Beef)", "per_100g": 6.2},
        ],
    },
    "vitamin_b5": {
        "name": "维生素B5 (Vitamin B5 / Pantothenic Acid)",
        "unit": "mg",
        "rda_per_day": 5.0,
        "time_window_days": 1,
        "reference": "IOM AI 5 mg/day; water-soluble, widely distributed in foods, daily assessment recommended.",
        "deficiency_diseases": [
            "灼热足综合征 Burning Feet Syndrome（足部灼热、麻木）",
            "慢性疲劳、头痛、易激惹",
            "肾上腺功能受损（泛酸为辅酶A前体，影响类固醇合成）",
        ],
        "sources": [
            {"food": "鸡蛋 (Egg)", "per_100g": 1.4},
            {"food": "蘑菇 (Mushrooms)", "per_100g": 1.5},
            {"food": "鸡胸肉 (Chicken Breast)", "per_100g": 0.9},
            {"food": "牛油果 (Avocado)", "per_100g": 1.4},
            {"food": "牛肝 (Beef Liver)", "per_100g": 7.0},
        ],
    },
    "vitamin_b6": {
        "name": "维生素B6 (Vitamin B6 / Pyridoxine)",
        "unit": "mg",
        "rda_per_day": 1.3,
        "time_window_days": 1,
        "reference": "IOM RDA 1.3 mg/day; water-soluble, tissue stores last only days, daily intake important.",
        "deficiency_diseases": [
            "周围神经病变（手足麻木、感觉异常）",
            "小细胞性贫血（影响血红素合成）",
            "脂溢性皮炎、唇干裂",
            "抑郁、意识模糊（影响血清素合成）",
            "高同型半胱氨酸血症（心血管风险升高）",
        ],
        "sources": [
            {"food": "鸡胸肉 (Chicken Breast)", "per_100g": 0.90},
            {"food": "土豆 (Potato)", "per_100g": 0.44},
            {"food": "香蕉 (Banana)", "per_100g": 0.37},
            {"food": "三文鱼 (Salmon)", "per_100g": 0.94},
            {"food": "牛肉 (Beef)", "per_100g": 0.40},
        ],
    },
    "vitamin_b7": {
        "name": "维生素B7 (Vitamin B7 / Biotin)",
        "unit": "mcg",
        "rda_per_day": 30.0,
        "time_window_days": 7,
        "reference": "IOM AI 30 mcg/day; some liver storage allows flexible intake; weekly window is appropriate.",
        "deficiency_diseases": [
            "脱发、眉毛稀疏",
            "指甲脆裂",
            "脂溢性皮炎（眼周、鼻周红斑）",
            "神经症状（抑郁、幻觉、四肢麻木）",
        ],
        "sources": [
            {"food": "鸡蛋 (Egg Cooked)", "per_100g": 20.0},
            {"food": "红薯 (Sweet Potato)", "per_100g": 4.9},
            {"food": "杏仁 (Almonds)", "per_100g": 64.0},
            {"food": "花生 (Peanuts)", "per_100g": 34.0},
            {"food": "牛肝 (Beef Liver)", "per_100g": 36.8},
        ],
    },
    "vitamin_b9": {
        "name": "维生素B9 (Vitamin B9 / Folate)",
        "unit": "mcg_dfe",
        "rda_per_day": 400.0,
        "time_window_days": 7,
        "reference": "IOM RDA 400 mcg DFE/day; body stores ~5-10 mg (months supply), but weekly tracking reflects intake patterns.",
        "deficiency_diseases": [
            "巨幼细胞性贫血 Megaloblastic Anemia（疲劳、气短、面色苍白）",
            "神经管缺陷 Neural Tube Defects（孕早期缺乏 → 脊柱裂、无脑儿）",
            "高同型半胱氨酸血症（心血管病、中风风险升高）",
            "认知功能减退、抑郁",
        ],
        "sources": [
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 146.0},
            {"food": "西兰花 (Broccoli)", "per_100g": 63.0},
            {"food": "鸡蛋 (Egg)", "per_100g": 44.0},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 181.0},
            {"food": "牛肝 (Beef Liver)", "per_100g": 290.0},
        ],
    },
    "vitamin_b12": {
        "name": "维生素B12 (Vitamin B12 / Cobalamin)",
        "unit": "mcg",
        "rda_per_day": 2.4,
        "time_window_days": 30,
        "reference": "IOM RDA 2.4 mcg/day; liver stores 1-5 mg, depletion takes 2-5 years; 30-day window reflects physiological buffer.",
        "deficiency_diseases": [
            "巨幼细胞性贫血（乏力、气短、面色苍白）",
            "脊髓亚急性联合变性 Subacute Combined Degeneration（下肢无力、感觉异常、共济失调）",
            "周围神经病变（手足麻木、刺痛）",
            "认知障碍、痴呆（尤其老年人）",
            "高同型半胱氨酸血症",
        ],
        "sources": [
            {"food": "牛肉 (Beef)", "per_100g": 2.6},
            {"food": "鸡蛋 (Egg)", "per_100g": 1.1},
            {"food": "牛奶 (Milk)", "per_100g": 0.45},
            {"food": "三文鱼 (Salmon)", "per_100g": 3.2},
            {"food": "牛肝 (Beef Liver)", "per_100g": 59.3},
        ],
    },
    # ── Macrominerals ─────────────────────────────────────────────────────────
    "calcium": {
        "name": "钙 (Calcium)",
        "unit": "mg",
        "rda_per_day": 1000.0,
        "time_window_days": 1,
        "reference": "IOM RDA 1000 mg/day for adults 19-50; bone remodeling requires consistent daily supply.",
        "deficiency_diseases": [
            "骨质疏松症 Osteoporosis（骨折风险大幅升高）",
            "低钙血症 Hypocalcemia（手足抽搐、肌肉痉挛、心律失常）",
            "佝偻病（儿童）、骨软化症（成人）",
        ],
        "sources": [
            {"food": "牛奶 (Milk)", "per_100g": 120.0},
            {"food": "老豆腐 (Firm Tofu)", "per_100g": 350.0},
            {"food": "希腊酸奶 (Greek Yogurt)", "per_100g": 110.0},
            {"food": "西兰花 (Broccoli)", "per_100g": 47.0},
            {"food": "硬奶酪 (Hard Cheese)", "per_100g": 720.0},
        ],
    },
    "phosphorus": {
        "name": "磷 (Phosphorus)",
        "unit": "mg",
        "rda_per_day": 700.0,
        "time_window_days": 1,
        "reference": "IOM RDA 700 mg/day; essential for ATP, bone matrix, and cell membranes; daily intake required.",
        "deficiency_diseases": [
            "低磷血症 Hypophosphatemia（肌无力、骨痛）",
            "骨软化症（磷是羟基磷灰石成分）",
            "溶血性贫血（红细胞ATP耗竭）",
            "严重时呼吸衰竭（呼吸肌无力）",
        ],
        "sources": [
            {"food": "三文鱼 (Salmon)", "per_100g": 371.0},
            {"food": "葵花籽 (Sunflower Seeds)", "per_100g": 660.0},
            {"food": "鸡胸肉 (Chicken Breast)", "per_100g": 220.0},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 180.0},
            {"food": "牛奶 (Milk)", "per_100g": 93.0},
        ],
    },
    "magnesium": {
        "name": "镁 (Magnesium)",
        "unit": "mg",
        "rda_per_day": 400.0,
        "time_window_days": 1,
        "reference": "IOM RDA 310-420 mg/day; cofactor for >300 enzymes; daily intake recommended as renal excretion is rapid.",
        "deficiency_diseases": [
            "低镁血症（肌肉痉挛、抖动、手足麻木）",
            "心律失常（室颤风险）",
            "高血压、偏头痛",
            "焦虑、抑郁、失眠",
            "胰岛素抵抗，2型糖尿病风险升高",
        ],
        "sources": [
            {"food": "杏仁 (Almonds)", "per_100g": 270.0},
            {"food": "燕麦 (Oats)", "per_100g": 177.0},
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 87.0},
            {"food": "黑豆(熟) (Black Beans Cooked)", "per_100g": 60.0},
            {"food": "香蕉 (Banana)", "per_100g": 27.0},
        ],
    },
    "potassium": {
        "name": "钾 (Potassium)",
        "unit": "mg",
        "rda_per_day": 3400.0,
        "time_window_days": 1,
        "reference": "IOM AI 2600-3400 mg/day; critical for cell membrane potential; kidneys regulate tightly, daily intake essential.",
        "deficiency_diseases": [
            "低钾血症 Hypokalemia（肌无力、疲劳、便秘）",
            "心律失常（严重可危及生命）",
            "横纹肌溶解（极度低钾）",
            "高血压风险升高（钾拮抗钠的升压效应）",
        ],
        "sources": [
            {"food": "香蕉 (Banana)", "per_100g": 358.0},
            {"food": "红薯(熟) (Sweet Potato Cooked)", "per_100g": 475.0},
            {"food": "土豆 (Potato)", "per_100g": 379.0},
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 466.0},
            {"food": "牛油果 (Avocado)", "per_100g": 485.0},
        ],
    },
    "sodium": {
        "name": "钠 (Sodium)",
        "unit": "mg",
        "rda_per_day": 1500.0,
        "time_window_days": 1,
        "reference": "IOM AI 1500 mg/day (adequate intake); extracellular fluid balance, nerve conduction; daily monitoring.",
        "deficiency_diseases": [
            "低钠血症 Hyponatremia（头痛、恶心、精神混乱）",
            "严重低钠：癫痫发作、脑水肿、昏迷",
            "肌肉痉挛、极度疲劳（大量出汗后未补钠）",
        ],
        "sources": [
            {"food": "食盐 (Table Salt)", "per_100g": 38000.0},
            {"food": "酱油 (Soy Sauce)", "per_100g": 5700.0},
            {"food": "硬奶酪 (Hard Cheese)", "per_100g": 620.0},
            {"food": "面包 (Bread)", "per_100g": 491.0},
        ],
    },
    # ── Trace Minerals ────────────────────────────────────────────────────────
    "iron": {
        "name": "铁 (Iron)",
        "unit": "mg",
        "rda_per_day": 8.0,
        "time_window_days": 1,
        "reference": "IOM RDA 8 mg/day for adult men; hemoglobin synthesis and oxygen transport require consistent supply.",
        "deficiency_diseases": [
            "缺铁性贫血（全球最常见营养缺乏病）：面色苍白、乏力、气短",
            "认知功能减退、注意力不集中（儿童发育受损）",
            "免疫力下降，反复感染",
            "不宁腿综合征 Restless Legs Syndrome",
            "头发稀疏、指甲扁平（匙状甲）",
        ],
        "sources": [
            {"food": "牛肉 (Beef)", "per_100g": 2.6},
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 3.6},
            {"food": "老豆腐 (Firm Tofu)", "per_100g": 2.7},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 3.3},
            {"food": "牛肝 (Beef Liver)", "per_100g": 6.5},
        ],
    },
    "zinc": {
        "name": "锌 (Zinc)",
        "unit": "mg",
        "rda_per_day": 11.0,
        "time_window_days": 1,
        "reference": "IOM RDA 8-11 mg/day; no dedicated storage organ, body pool turns over rapidly requiring daily intake.",
        "deficiency_diseases": [
            "生长发育迟缓（儿童身材矮小）",
            "性腺机能减退，不育",
            "伤口愈合缓慢",
            "味觉减退 Dysgeusia、嗅觉减退",
            "脱发、皮炎",
            "免疫力下降，易感染",
        ],
        "sources": [
            {"food": "牛肉 (Beef)", "per_100g": 7.0},
            {"food": "鸡蛋 (Egg)", "per_100g": 1.3},
            {"food": "腰果 (Cashews)", "per_100g": 5.6},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 1.3},
            {"food": "牡蛎 (Oysters)", "per_100g": 78.6},
        ],
    },
    "selenium": {
        "name": "硒 (Selenium)",
        "unit": "mcg",
        "rda_per_day": 55.0,
        "time_window_days": 30,
        "reference": "IOM RDA 55 mcg/day; body pool ~15 mg in skeletal muscle, depletion over months; 30-day window appropriate.",
        "deficiency_diseases": [
            "克山病 Keshan Disease（心肌病、心律失常，地方性）",
            "大骨节病 Kashin-Beck Disease（关节软骨变性）",
            "甲状腺功能减退（硒是脱碘酶辅因子）",
            "抗氧化能力下降，氧化应激相关疾病风险升高",
        ],
        "sources": [
            {"food": "鸡蛋 (Egg)", "per_100g": 30.8},
            {"food": "金枪鱼罐头 (Canned Tuna)", "per_100g": 80.4},
            {"food": "三文鱼 (Salmon)", "per_100g": 36.5},
            {"food": "牛肉 (Beef)", "per_100g": 14.2},
            {"food": "巴西坚果 (Brazil Nut 1粒≈5g)", "per_100g": 1917.0},
        ],
    },
    "iodine": {
        "name": "碘 (Iodine)",
        "unit": "mcg",
        "rda_per_day": 150.0,
        "time_window_days": 14,
        "reference": "IOM RDA 150 mcg/day; thyroid gland stores ~15 mg (months reserve), but dietary variability warrants 2-week tracking.",
        "deficiency_diseases": [
            "甲状腺肿大 Goiter（颈部肿块）",
            "甲状腺功能减退（怕冷、疲劳、体重增加、便秘）",
            "克汀病 Cretinism（孕期缺碘 → 先天性智力障碍、聋哑）",
            "流产、死胎风险升高",
        ],
        "sources": [
            {"food": "碘盐 (Iodized Salt)", "per_100g": 4500.0},
            {"food": "海带 (Kelp)", "per_100g": 2984.0},
            {"food": "鳕鱼 (Cod Fish)", "per_100g": 170.0},
            {"food": "牛奶 (Milk)", "per_100g": 56.0},
            {"food": "虾 (Shrimp)", "per_100g": 40.0},
        ],
    },
    "copper": {
        "name": "铜 (Copper)",
        "unit": "mg",
        "rda_per_day": 0.9,
        "time_window_days": 7,
        "reference": "IOM RDA 0.9 mg/day; liver storage buffer allows weekly intake window without deficiency risk.",
        "deficiency_diseases": [
            "贫血（铜缺乏性，对铁剂治疗无效）",
            "中性粒细胞减少症，免疫力下降",
            "骨质疏松，骨折",
            "神经系统病变（脊髓病、周围神经病）",
            "色素脱失（铜是酪氨酸酶辅因子）",
        ],
        "sources": [
            {"food": "腰果 (Cashews)", "per_100g": 2.19},
            {"food": "黑巧克力70% (Dark Chocolate 70%)", "per_100g": 1.77},
            {"food": "花生 (Peanuts)", "per_100g": 1.14},
            {"food": "牛肝 (Beef Liver)", "per_100g": 9.76},
            {"food": "牡蛎 (Oysters)", "per_100g": 7.6},
        ],
    },
    "manganese": {
        "name": "锰 (Manganese)",
        "unit": "mg",
        "rda_per_day": 2.3,
        "time_window_days": 7,
        "reference": "IOM AI 1.8-2.3 mg/day; stored in liver and bone; weekly window reflects moderate physiological buffering.",
        "deficiency_diseases": [
            "骨骼发育异常（骨形成受损、关节畸形）",
            "葡萄糖耐量受损（影响胰岛素合成）",
            "皮疹、毛发颜色改变",
            "生殖功能异常",
        ],
        "sources": [
            {"food": "燕麦 (Oats)", "per_100g": 3.63},
            {"food": "糙米(熟) (Brown Rice Cooked)", "per_100g": 0.97},
            {"food": "菠菜(熟) (Spinach Cooked)", "per_100g": 0.85},
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 0.49},
            {"food": "红茶(泡) (Black Tea Brewed)", "per_100g": 0.52},
        ],
    },
    "chromium": {
        "name": "铬 (Chromium)",
        "unit": "mcg",
        "rda_per_day": 35.0,
        "time_window_days": 30,
        "reference": "IOM AI 25-35 mcg/day; enhances insulin action; body stores in multiple tissues, 30-day window is appropriate.",
        "deficiency_diseases": [
            "葡萄糖耐量受损（血糖调节失常）",
            "胰岛素抵抗，2型糖尿病风险升高",
            "血脂异常（LDL升高、HDL降低）",
        ],
        "sources": [
            {"food": "西兰花 (Broccoli)", "per_100g": 11.0},
            {"food": "牛肉 (Beef)", "per_100g": 2.0},
            {"food": "全麦面包 (Whole Wheat Bread)", "per_100g": 4.5},
            {"food": "橙汁 (Orange Juice)", "per_100g": 2.2},
            {"food": "土豆 (Potato)", "per_100g": 0.3},
        ],
    },
    "molybdenum": {
        "name": "钼 (Molybdenum)",
        "unit": "mcg",
        "rda_per_day": 45.0,
        "time_window_days": 30,
        "reference": "IOM RDA 45 mcg/day; cofactor for sulfite oxidase and xanthine oxidase; long biological half-life, monthly window.",
        "deficiency_diseases": [
            "亚硫酸盐中毒（亚硫酸盐氧化酶活性下降 → 神经损伤）",
            "高尿酸血症风险（黄嘌呤氧化酶失调）",
            "（天然食物中极为罕见缺乏）",
        ],
        "sources": [
            {"food": "扁豆(熟) (Lentils Cooked)", "per_100g": 155.0},
            {"food": "黑豆(熟) (Black Beans Cooked)", "per_100g": 130.0},
            {"food": "鹰嘴豆(熟) (Chickpeas Cooked)", "per_100g": 109.0},
            {"food": "燕麦 (Oats)", "per_100g": 85.0},
        ],
    },
    "fluoride": {
        "name": "氟 (Fluoride)",
        "unit": "mg",
        "rda_per_day": 4.0,
        "time_window_days": 30,
        "reference": "IOM AI 3-4 mg/day; incorporated into tooth enamel and bone over months; 30-day window appropriate.",
        "deficiency_diseases": [
            "龋齿 Dental Caries（牙釉质保护减弱，蛀牙风险大幅增加）",
            "骨密度下降，骨折风险升高",
        ],
        "sources": [
            {"food": "含氟自来水 (Fluoridated Water)", "per_100g": 0.07},
            {"food": "红茶(泡) (Black Tea Brewed)", "per_100g": 0.37},
            {"food": "沙丁鱼罐头(带骨) (Canned Sardines+Bones)", "per_100g": 0.88},
        ],
    },
    # ── Fatty Acids ───────────────────────────────────────────────────────────
    "omega3": {
        "name": "Omega-3脂肪酸 (Omega-3 Fatty Acids)",
        "unit": "g",
        "rda_per_day": 1.6,
        "time_window_days": 7,
        "reference": "IOM AI 1.1-1.6 g/day ALA; EPA/DHA tissue incorporation takes weeks, weekly window reflects physiological kinetics.",
        "deficiency_diseases": [
            "心血管疾病风险升高（心梗、中风）",
            "抑郁、焦虑（EPA/DHA是大脑结构成分）",
            "干眼症、视网膜功能减退",
            "慢性炎症状态（影响前列腺素平衡）",
            "婴幼儿脑发育受损（孕期/哺乳期缺乏）",
        ],
        "sources": [
            {"food": "三文鱼 (Salmon)", "per_100g": 2.26},
            {"food": "核桃 (Walnuts)", "per_100g": 9.08},
            {"food": "沙丁鱼罐头 (Canned Sardines)", "per_100g": 1.48},
            {"food": "亚麻籽 (Flaxseeds)", "per_100g": 22.8},
            {"food": "鸡蛋 (Egg)", "per_100g": 0.1},
        ],
    },
}

# Ordered list of all nutrient keys (used for template generation)
ALL_NUTRIENT_KEYS: list[str] = list(NUTRIENTS.keys())
